package com.dmikhov.androidapp1.utils

/**
 * Created by dmikhov on 15.11.2016.
 */
object Const {
    val PRESENTER_CACHE_MAIN_ACTIVITY = "PRESENTER_CACHE_MAIN_ACTIVITY"
    val PRESENTER_CACHE_DELIVERY_ACTIVITY = "PRESENTER_CACHE_DELIVERY_ACTIVITY"

    val EXTRA_SELECT_DELIVERY_ID = "EXTRA_SELECT_DELIVERY_ID"
}
